from os import environ as env

from dotenv import load_dotenv

load_dotenv()

DEBUG = bool(env["DEBUG"])

MAXIMUM_WITHDRAW_AMOUNT = float(env["MAXIMUM_WITHDRAW_AMOUNT"])

MINIMUM_WITHDRAW_AMOUNT = float(env["MINIMUM_WITHDRAW_AMOUNT"])

MAXIMUM_DEPOSIT_AMOUNT = float(env["MAXIMUM_DEPOSIT_AMOUNT"])

MINIMUM_DEPOSIT_AMOUNT = float(env["MINIMUM_DEPOSIT_AMOUNT"])

MAXIMUM_ACCOUNT_BALANCE_LIMIT = float(env["MAXIMUM_ACCOUNT_BALANCE_LIMIT"])

WITHDRAW_DAY_LIMIT = int(env["WITHDRAW_DAY_LIMIT"])

DEPOSIT_DAY_LIMIT = int(env["DEPOSIT_DAY_LIMIT"])

INPUT_FILE_PATH = str(env["INPUT_FILE_PATH"])
